server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:online_banking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:online_banking}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework: DEBUG
    com.onlinebanking: DEBUG
    org.flywaydb: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
  issuer: online-banking-app

security:
  aes:
    key: ${AES_SECRET}
